### ISSUE TITLE
No way to add cargo ships other than creative mode

### ISSUE THREAD

**Issue by lekkimsm2500** [Keranik/COI-Extended#22]
I would be really appreciative if you could look into an alternative way to add cargo ships, other than having to use creative mode. If all you need are more ships, resorting to creative mode seems a little excessive. 

Also, thank you so much for picking up on the old mod, and for making this great successor of yours. It works amazingly!

**Comment by Keranik** [comment]
Do you mean other than the cargo dock that lets you build your own ships?

**Comment by lekkimsm2500** [comment]
Sorry, i forgot to mention it was in conjunction with COI-Extended. 

But yes, other than the drydock in extended, and OTHER than the creative mode function in your cheat mod, it would be super helpful to have the option to add cargo ships, much like in the same sense of adding products to shipyard or changing vehicle limit. 

That if, it's technically feasible of course.

**Comment by Keranik** [comment]
We need to be able to set the number of available cargo ships with an integer instead of needing to add 99 at a time and ruining the game by hitting creative mode when all you wanted is a few more ships?

For now you can add_cargo_ship in console of COI:E will give you one more ship each time, but I agree that we need a way in the cheat menu to just set your number of available cargo ships.  I can handle that no problem.

**Comment by lekkimsm2500** [comment]
I didn't even know you could add ships from the console, but that's a handy tip for sure. 

But thanks for looking into it!

**Comment by Keranik** [comment]
okay in patch next time
