### ISSUE TITLE
Possibly add Equinox Armageddon with Ilmenite Ore

### ISSUE THREAD

**Issue by FormBurden** [Keranik/COI-Extended#33]
Could you possibly add to either the mod and/or the Hub the Hub map Equinox Armageddon with your mods Ilmenite Ore?

Thought maybe the map editor could do it, but I guess there's no way to input modded resources into the maps using map editor. Unless you used some special tool to do it that is outside the game?

https://hub.coigame.com/Map/Detail/63

Thanks for your time, and the mod is super fun!

**Comment by Keranik** [comment]
First click on 'New Game' to initialize the mod, then return to the main menu and use the Map Editor.

You'll find the new ore there, add as much as you'd wish to any map :)

**Comment by FormBurden** [comment]
> First click on 'New Game' to initialize the mod, then return to the main menu and use the Map Editor.
> 
> You'll find the new ore there, add as much as you'd wish to any map :)

Are you able to do it right now? Not sure if one of the recent updates caused the Mods to not work while in Map Editor, because I did what you stated and nothing. Not sure if it's a Linux thing? I am using Arch-Linux. But everyone on the game works correctly. Also, all of the COIE custom maps don't show in the Map Editor either.

**Comment by Keranik** [comment]
Custom maps don't show in the Map Editor because they are stored in the Maps folder in the mods directory.  The base game doesn't look for them there.  You can simply copy them from your COIExtended/Maps directory, to the game's regular /Maps directory, edit them there, and then either keep it there, or move it back to your COIExtended/Maps directory.

The "Mineable Resources" on the bottom toolbar is not the list of resources that can be added to the game.  You need to pick a terrain feature (can include mineable resources) and then you need to locate the list on the right to pick which material you want to be included.

**Comment by FormBurden** [comment]
Oh... I see. Yep, you are right, I now see the Ore. Hmm, maybe you should put a note in the description of your mod so others can find find this useful info since it's kind of hidden in the game and not in "Mineable Resources". Thanks for the info! :)
