### ISSUE TITLE
Custom world generation and settings info

### ISSUE THREAD

**Issue by clausberner** [Keranik/COI-Extended#9]
Downloaded the newest version 6.0 you released, and use all three of the mods.
Tried to set some easily recognizable settings:
![image](https://github.com/Keranik/COI-Extended/assets/12047675/2e44d2f4-3911-4021-866f-a6e4e0ac8494)
![image](https://github.com/Keranik/COI-Extended/assets/12047675/f146b9b9-0dcf-45d1-8ebe-f4017a27cc84)
But no matter what i change the map does not change, the location position varies, but in a way that makes it seem the settings is hard locked. I also never get more than two cargo ships and the world seems rather empty. You can also see connections being made to nowhere like on the west side of the world map in the picture.

While trying to change the world map i also encountered a bug with the settings information. After exiting to main menu, the setting explanations don't appear when hovering over the "i" and all options for map shape are also gone, no drop down menu appears.

**Comment by Keranik** [comment]
What is happening is that map generation is failing, but in order to save you from the program crashing, it is generating some type of default map to keep you within the game.  The "missing" locations are a result of the way that the cheat auto-explores the map, and those will fix themselves on a game save/load.  Because you have posted your settings, I can now fix that issue and I will resolve this for the next patch.

I appreciate you posting your map settings along with this Issue as it has allowed me to fix it quickly.  Again, thanks for your time; this should be updated in the next patch.
